### PR TITLE
feat: add missing configuration parameters and add validations for plan-time

### PR DESCRIPTION
**Pull request by MatthewLemmond**
### Description

Add parameters that are documented in https://cloud.ibm.com/docs/databases-for-postgresql?topic=databases-for-postgresql-changing-configuration&interface=api but are not listed in the API docs

Resolves https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/issues/422
fixes https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/issues/423

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by vburckhardt** [comment]
Added coverage in tests + merged with main + fixed https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/issues/423

**Comment by ocofaigh** [comment]
@MatthewLemmond was there a reason for bumping common-dev-assets here? The new version of it has terraform 1.6.6 in it, and it fails pipeline because some of the versions of modules in the examples are not at latest and wont ru on tf 1.6. This renovate PR needs to be merge first to be able to go to 1.6 -> https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/pull/363

I suggest to remove common-dev-assets from this pr so it can pass pipeline

**Review by ocofaigh — DISMISSED** [review]
@MatthewLemmond same changes are needed in the fscloud submodule

**Comment by vburckhardt** [comment]
@ocofaigh - I bumped common-dev-assets.

**Comment by vburckhardt** [comment]
@MatthewLemmond - some issues with transitive dependencies in examples

**Comment by MatthewLemmond** [comment]
Upgrade test failed due to the new parameters being added and used in the complete example, skipped. Here is the run with the upgrade test failure: https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/actions/runs/9321397057/job/25660455564

**Review by vburckhardt — APPROVED** [review]

**Pull request merged**
