### PR TITLE
test: new host model with 4G memory PITR

### PR DESCRIPTION
**Pull request by Ak-sky**
### Description

Updated PITR example.

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Ak-sky** [comment]
PR test failing with

> Error: PointInTimeRecoveryDBExample 2024-07-16T05:23:17Z logger.go:66: │ Error: [ERROR] Error creating database instance: Please contact the Service Provider for this error. [400, Bad Request] We were unable to complete your request: group.memory requires a minimum of 12288 megabytes, group.memory must be an increment of 384 megabytes. Try again with valid values or contact support if the issue persists.

**Comment by Ak-sky** [comment]
> PR test failing with
> 
> > Error: PointInTimeRecoveryDBExample 2024-07-16T05:23:17Z logger.go:66: │ Error: [ERROR] Error creating database instance: Please contact the Service Provider for this error. [400, Bad Request] We were unable to complete your request: group.memory requires a minimum of 12288 megabytes, group.memory must be an increment of 384 megabytes. Try again with valid values or contact support if the issue persists.

@shemau, Continuous Test failed with the below error `error occurred:\n\t* member group memory must be >= 4096 and <= 114688` so I updated the `member_memory_mb` to 4096, now PR test faile with `group.memory` should  12288 MB , what could be the issue?

> TestRunPointInTimeRecoveryDBExample 2024-07-16T00:39:20Z logger.go:66: │ Error: ---
> TestRunPointInTimeRecoveryDBExample 2024-07-16T00:39:20Z logger.go:66: │ id: terraform-23dab597
> TestRunPointInTimeRecoveryDBExample 2024-07-16T00:39:20Z logger.go:66: │ summary: "1 error occurred:\n\t* member group memory must be >= 4096 and <= 114688
> TestRunPointInTimeRecoveryDBExample 2024-07-16T00:39:20Z logger.go:66: │   in increments of 128\n\n"
> TestRunPointInTimeRecoveryDBExample 2024-07-16T00:39:20Z logger.go:66: │ severity: error
> TestRunPointInTimeRecoveryDBExample 2024-07-16T00:39:20Z logger.go:66: │ resource: ibm_database
> TestRunPointInTimeRecoveryDBExample 2024-07-16T00:39:20Z logger.go:66: │ operation: CustomizeDiff
> TestRunPointInTimeRecoveryDBExample 2024-07-16T00:39:20Z logger.go:66: │ component:
> TestRunPointInTimeRecoveryDBExample 2024-07-16T00:39:20Z logger.go:66: │   name: [github.com/IBM-Cloud/terraform-provider-ibm](http://github.com/IBM-Cloud/terraform-provider-ibm)
> TestRunPointInTimeRecoveryDBExample 2024-07-16T00:39:20Z logger.go:66: │   version: 1.67.1
> TestRunPointInTimeRecoveryDBExample 2024-07-16T00:39:20Z logger.go:66: │ ---
> TestRunPointInTimeRecoveryDBExample 2024-07-16T00:39:20Z logger.go:66: │

**Comment by shemau** [comment]
It seems that I missed that the PITR test was using 3G during the change to the hosting model upgrade.

The upgrade to the new shared compute model requires 4G minimum memory. This is fairly well documented in various location, including [here](https://www.ibm.com/blog/announcement/ibm-cloud-databases-hosting-model/#) or [here](https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-hosting-models&interface=ui).

I can not find any specific guidance on memory or cpu for PITR. The [mongodb](https://cloud.ibm.com/docs/databases-for-mongodb?topic=databases-for-mongodb-pitr&interface=terraform) examples uses 14G/6 cpu with the old model.

I can only conclude from this that for PITR instances 12G of memory is required.

The best I can do is take a guess. The ibm_database resource has multiple checks, the first check is that multi tenant must be more than 4G. At 3G this failed and the process errored out. The second check is that PITR has 12G, so once it is upgrade to 4G it errors out on the PITR check.

None of this makes any sense, the PR with PITR 3G worked last week. The PITR should only be done in CI (not PR pipeline). So you should be able to put ANY value in PITR and should pass PR, because it is not run. So why is it failing here?

**Comment by Ak-sky** [comment]
> It seems that I missed that the PITR test was using 3G during the change to the hosting model upgrade.
> 
> The upgrade to the new shared compute model requires 4G minimum memory. This is fairly well documented in various location, including [here](https://www.ibm.com/blog/announcement/ibm-cloud-databases-hosting-model/#) or [here](https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-hosting-models&interface=ui).
> 
> I can not find any specific guidance on memory or cpu for PITR. The [mongodb](https://cloud.ibm.com/docs/databases-for-mongodb?topic=databases-for-mongodb-pitr&interface=terraform) examples uses 14G/6 cpu with the old model.
> 
> I can only conclude from this that for PITR instances 12G of memory is required.
> 
> The best I can do is take a guess. The ibm_database resource has multiple checks, the first check is that multi tenant must be more than 4G. At 3G this failed and the process errored out. The second check is that PITR has 12G, so once it is upgrade to 4G it errors out on the PITR check.
> 
> None of this makes any sense, the PR with PITR 3G worked last week. The PITR should only be done in CI (not PR pipeline). So you should be able to put ANY value in PITR and should pass PR, because it is not run. So why is it failing here?

@ocofaigh how come the other_tests are running in PR?

**Comment by ocofaigh** [comment]
@Ak-sky Update to the latest common-dev-assets as a fix was added 2 days ago to ensure other_tests.go dont run in PRs. There was a regression introduced last week, but latest common-dev-assets has a fix

**Comment by Ak-sky** [comment]
- Locally PITR test is still failing with `12288` MB.
   
   image

- And also failing with `12288` MB and passing `earliest-pitr-timestamp` using `ic cdb pg earliest-pitr-timestamp <pg-instance-crn>`

   image

- With below errors
  - 1st error 
      
     image


   - 2nd error
     
     image

- In UI it shows both the PITR instance provisioning is stuck in `Provision in progress` status.

   image

**Comment by shemau** [comment]
That would appear to be two different errors (potentially the same root cause):

No timestamp failed with a timeout, probably on the ibm_database resource. This looked odd with a `space` character rather than an empty string or null.
With timestamp, it failed with an error finding the database connection information. I would have expected this to come from the ibm_database_connection resource in the module, but it also seems to originate from the ibm_database resource. 

It is probably worth raising an issue against the provider or asking in slack to see if PITR has any issues.

**Comment by Ak-sky** [comment]
PITR test passed

PITR_passed

**Review by shemau — APPROVED** [review]
LGTM.

A discussion was had around the 12G limit. The property is described as `per member`; yet the provider implementation appears to support that it is total memory. So 3 members requires 12G of memory to achieve the minimum 4G per member for multitenant.

**Pull request merged**
