### PR TITLE
fix: update postgresql configuration

### PR DESCRIPTION
**Pull request by iamar7**
### Description

Added two extra configuration `log_disconnections` and `log_connections` so that the module be able to clear db scan by tenable.

https://github.ibm.com/GoldenEye/issues/issues/9011

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Added two extra configuration `log_disconnections` and `log_connections`.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — CHANGES_REQUESTED** [review]
Maybe we should update the fscloud example to actually use some of the optional `configuration` parameters? Ideally set them to the same as Dreadnought have since they have done audit scanning on the Postgres instances

**Comment by iamar7** [comment]
> Maybe we should update the fscloud example to actually use some of the optional `configuration` parameters? Ideally set them to the same as Dreadnought have since they have done audit scanning on the Postgres instances

The dreadnaught team suggested to keep both `log_connections` and `log_disconnections` as `on`.

**Review by ocofaigh — CHANGES_REQUESTED** [review]
Can we add variable validation for the new `log_connections` and `log_disconnections`? I'm assuming the allowed values are `on` and `off` ?
There may be other parameters in that configuration map we could add too?

**Comment by iamar7** [comment]
> Can we add variable validation for the new `log_connections` and `log_disconnections`? I'm assuming the allowed values are `on` and `off` ? There may be other parameters in that configuration map we could add validation for too?

Shall I add the validation of other parameters from [here](https://cloud.ibm.com/apidocs/cloud-databases-api/cloud-databases-api-v4#setdatabaseconfiguration-request)?

**Comment by vburckhardt** [comment]
Hi @iamar7 - could we add them all - I opened this related ticket today https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/issues/422

**Comment by iamar7** [comment]
> Hi @iamar7 - could we add them all - I opened this related ticket today #422

I saw the PR already raised for that issue [here](https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/pull/424).

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
