### PR TITLE
feat: host_flavor can take a specific id as  multitenant

### PR DESCRIPTION
**Pull request by Ak-sky**
### Description

Host_flavor can take a specific id as multitenant.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

In this release-
If host_flavor is set to `multitenant`, this will place the database on a logically separated, multi-tenant machine with minimum resource configurations required for `multitenant` config.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by shemau — CHANGES_REQUESTED** [review]
Is a whole new example, spinning up yet another database instance on every single PR and CI pipeline run necessary?

Should we change the basic test to use 8G of memory and change one of the two `other_test.go` tests to use multitenant? It is also less than

**Comment by Ak-sky** [comment]
> Is a whole new example, spinning up yet another database instance on every single PR and CI pipeline run necessary?
> 
> Should we change the basic test to use 8G of memory and change one of the two `other_test.go` tests to use multitenant? It is also less than

@shemau I thought so too but then we just have to add `member_memory_mb` variable in basic example, that should do it.

**Comment by shemau** [comment]
IMHO that would be less ongoing maintenance (less code) and by using other_test.go would also appropriately reduce the number of instances spun up for testing.

**Review by shemau — APPROVED** [review]
LGTM

**Pull request merged**
