### PR TITLE
Complete example fails to plan

### PR DESCRIPTION
**Pull request by shemau**
### Description

Update the vpe gateway module inputs to match 4.x.x variables in the complete example

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by shemau** [comment]
It may be necessary to skip upgrade test, since the base code on the main branch is broken.

Before doing this I am running tests locally.

**Comment by shemau** [comment]
Local tests were successful following a plan, apply, plan, destroy cycle for the complete example.

Due to the issues on the main branch this commit should be merged as one off without upgrade testing. Future PRs should then work with upgrade testing.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
