### PR TITLE
refactor: KMS cleanup

### PR DESCRIPTION
**Pull request by jor2**
### Description

WIP
https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/issues/541

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by jor2** [comment]
skipping upgrade test:


````
TestRunStandardUpgradeSolution 2024-12-16T14:56:30Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: Cycle: module.postgresql_db.module.postgresql_db.data.ibm_database_connection.database_connection (expand), time_sleep.wait_for_authorization_policy[0] (destroy), module.postgresql_db.module.postgresql_db.ibm_iam_authorization_policy.kms_policy[0], module.postgresql_db.module.postgresql_db.time_sleep.wait_for_authorization_policy (expand), module.postgresql_db.module.postgresql_db.ibm_database.postgresql_db (expand), module.postgresql_db.module.postgresql_db.data.ibm_database_connection.database_connection, module.postgresql_db.module.postgresql_db.ibm_iam_authorization_policy.kms_policy[0] (destroy deposed 48aaead3), time_sleep.wait_for_backup_kms_authorization_policy[0] (destroy), module.postgresql_db.module.postgresql_db.ibm_database.postgresql_db
````

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
